In [1]:
# problem 1 
import numpy as np 

print(np.__version__)


1.14.0


In [3]:
# problem 2
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# problem 3
arr = np.ones((3,3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# problem 4

arr[ arr % 2 == 1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
# problem 5

arr = np.arange(10)

arr[arr % 2 == 1] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
# problem 6

arr = np.arange(10)

out = np.where(arr % 2 == 1, -1, arr)

out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
# problem 7

arr = np.arange(10)

arr = arr.reshape(2, -1)

arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
# problem 8 

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.vstack([a,b])

c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
# problem 9 

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.hstack([a,b])

d = np.concatenate([a,b], axis=0)

c,d

(array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]), array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [20]:
# problem 10

a = np.array([1,2,3])

b = np.r_[ np.repeat(a, 3), np.tile(a,3) ]

b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [21]:
# problem 11

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)

c


array([2, 4])

In [22]:
# problem 12

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c = np.setdiff1d(a,b)

c

array([1, 2, 3, 4])

In [ ]:
# problem 13

